export const actionTypes = {
  BEGIN_API_CALL: "BEGIN_API_CALL",
  API_CALL_ERROR: "API_CALL_ERROR",

  CREATE_COURSE_SUCCESSFULLY: "CREATE_COURSE_SUCCESSFULLY",
  UPDATE_COURSE_SUCCESSFULLY: "UPDATE_COURSE_SUCCESSFULLY",
  DELETE_COURSE_OPTIMISTIC: "DELETE_COURSE_OPTIMISTIC",

  LOAD_COURSES_SUCCESSFULLY: "LOAD_COURSES_SUCCESSFULLY",
  LOAD_AUTHORS_SUCCESSFULLY: "LOAD_AUTHORS_SUCCESSFULLY",

}